"""Initial_db

Revision ID: 0cc3191ee40a
Revises: 
Create Date: 2025-03-22 09:52:20.820762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc3191ee40a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=True),
    sa.Column('game_description', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
