"""factions

Revision ID: 5019e83d1ed2
Revises: 6b5011382f39
Create Date: 2025-03-24 06:02:45.363432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5019e83d1ed2'
down_revision = '6b5011382f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faction',
    sa.Column('faction_id', sa.String(), nullable=False),
    sa.Column('faction_name', sa.String(), nullable=True),
    sa.Column('faction_game_edition_id', sa.String(), nullable=True),
    sa.Column('faction_alliance', sa.String(), nullable=True),
    sa.Column('faction_rules', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['faction_game_edition_id'], ['game_edition.game_edition_id'], ),
    sa.PrimaryKeyConstraint('faction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faction')
    # ### end Alembic commands ###
