"""Initial_db

Revision ID: 6b5011382f39
Revises: 96be63892767
Create Date: 2025-03-22 22:10:05.389951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5011382f39'
down_revision = '96be63892767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_edition',
    sa.Column('game_edition_id', sa.String(), nullable=False),
    sa.Column('game_edition_name', sa.String(), nullable=True),
    sa.Column('game_edition_game_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_edition_game_id'], ['game.game_id'], ),
    sa.PrimaryKeyConstraint('game_edition_id')
    )
    op.drop_table('game_editions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_editions',
    sa.Column('game_edition_id', sa.VARCHAR(), nullable=False),
    sa.Column('game_edition_name', sa.VARCHAR(), nullable=True),
    sa.Column('game_edition_game_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['game_edition_game_id'], ['game.game_id'], ),
    sa.PrimaryKeyConstraint('game_edition_id')
    )
    op.drop_table('game_edition')
    # ### end Alembic commands ###
