"""Initial_db

Revision ID: 96be63892767
Revises: 4e354c4adfdb
Create Date: 2025-03-22 22:05:11.897387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96be63892767'
down_revision = '4e354c4adfdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_editions',
    sa.Column('game_edition_id', sa.String(), nullable=False),
    sa.Column('game_edition_name', sa.String(), nullable=True),
    sa.Column('game_edition_game_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_edition_game_id'], ['game.game_id'], ),
    sa.PrimaryKeyConstraint('game_edition_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_editions')
    # ### end Alembic commands ###
